Repository tscircuit/core, pull requests merged in 2024-11, with the labels that each got.

#259 schematic box components now expand to fit label text
  lib/components/base-components/NormalComponent.ts
  lib/utils/schematic/getAllDimensionsForSchematicBox.ts
  tests/components/normal-components/__snapshots__/chip-layer-flip-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-schematic-position-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-without-portarrangement-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip.snap.svg
  tests/components/normal-components/__snapshots__/header-schematic.snap.svg
  tests/components/normal-components/__snapshots__/jumper-schematic.snap.svg
  tests/components/normal-components/chip-port-schematic-position.test.tsx
  tests/examples/__snapshots__/bug-high-port-number-schematic.snap.svg
  tests/examples/__snapshots__/example5-simple-circuit-schematic.snap.svg
  tests/utils/schematic/__snapshots__/schematicbox1.snap.svg
  tests/utils/schematic/__snapshots__/schematicbox2.snap.svg
Labels: 🙋 Bounty claim

#268 Added capacitor, inductor, diode and led schRotation support
  bun.lockb
  lib/components/base-components/PrimitiveComponent.ts
  lib/components/normal-components/Capacitor.ts
  lib/components/normal-components/Diode.ts
  lib/components/normal-components/Inductor.ts
  lib/components/normal-components/Led.ts
  package.json
  tests/components/normal-components/__snapshots__/inductor-schematic.snap.svg
  tests/components/normal-components/__snapshots__/rotated-components-schematic.snap.svg
  tests/components/normal-components/__snapshots__/rotated-resistor-schematic.snap.svg
  tests/components/normal-components/rotated-components.test.tsx
  tests/components/normal-components/rotated-resistor.test.tsx
Labels: 🙋 Bounty claim

#269 schematic_port.facing_direction is now more accurate
  lib/components/primitive-components/Port.ts
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
Labels: 🙋 Bounty claim

#253 Feat: error handling for missing footprint
  lib/components/base-components/NormalComponent.ts
  package.json
  tests/components/normal-components/resistor-with-footprint.test.tsx
  tests/components/normal-components/resistor-without-footprint.test.tsx
Labels: 🙋 Bounty claim

#314 fixed battery symbol not rendering
  lib/components/normal-components/Battery.ts
  tests/components/normal-components/__snapshots__/battery-schematic.snap.svg
Labels: 🙋 Bounty claim

#315 fixed non-port elements being added as ports for custom footprints
  lib/components/base-components/NormalComponent.ts
  tests/components/normal-components/__snapshots__/chip-layer-flip-schematic.snap.svg
  tests/components/normal-components/__snapshots__/custom-footprint-4-ports.snap.svg
  tests/components/normal-components/custom-footprint-4-ports.test.tsx
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
  tests/repros/__snapshots__/repro3-usb-port-footprint-schematic.snap.svg
Labels: 🙋 Bounty claim

#322 Refactor the trace so it does not get passed to the chip manufacturer part number and name
  bun.lockb
  lib/components/normal-components/Chip.ts
  lib/components/primitive-components/Trace/Trace.ts
  package.json
  tests/components/normal-components/__snapshots__/battery-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-complex-crossings-simplified-1-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-complex-schematic-crossings-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-layer-flip-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-override-footprint-ports-when-schPortArrangement-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-pin-alias-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-schematic-position-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-without-portarrangement-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip.snap.svg
  tests/components/normal-components/__snapshots__/custom-footprint-4-ports.snap.svg
  tests/components/normal-components/__snapshots__/diode-svg-snapshot-schematic.snap.svg
  tests/components/normal-components/__snapshots__/header-schematic.snap.svg
  tests/components/normal-components/__snapshots__/inductor-schematic.snap.svg
  tests/components/normal-components/__snapshots__/jumper-schematic.snap.svg
  tests/components/normal-components/__snapshots__/pin-header-schematic.snap.svg
  tests/components/normal-components/__snapshots__/potentiometer-schematic.snap.svg
  tests/components/normal-components/__snapshots__/pushbutton-schematic.snap.svg
  tests/components/normal-components/__snapshots__/rotated-components-schematic.snap.svg
  tests/components/primitive-components/__snapshots__/schematic-crossing-rendering-schematic.snap.svg
  tests/components/primitive-components/__snapshots__/trace-hint-schematic.snap.svg
  tests/components/primitive-components/__snapshots__/trace-schematic.snap.svg
  tests/examples/__snapshots__/bug-high-port-number-schematic.snap.svg
  tests/examples/__snapshots__/example3-2x2-keyboard-pcb.snap.svg
  tests/examples/__snapshots__/example4-kicad-schematic.snap.svg
  tests/examples/__snapshots__/example5-simple-circuit-schematic.snap.svg
  tests/examples/__snapshots__/example6-voltage-regulator-schematic.snap.svg
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
  tests/repros/__snapshots__/repro3-usb-port-footprint-schematic.snap.svg
  tests/repros/__snapshots__/repro4-schematic-trace-overlap-schematic.snap.svg
  tests/repros/__snapshots__/repro5-schematic-schematic.snap.svg
  tests/repros/repro5-schematic.test.tsx
Labels: 🙋 Bounty claim

#335 Resolved an issue where pin labels for the PinHeader component were not being drawn in SVG
  bun.lockb
  lib/components/base-components/NormalComponent.ts
  package.json
  tests/components/normal-components/__snapshots__/header-schematic.snap.svg
  tests/components/normal-components/header.test.tsx
Labels: 🙋 Bounty claim

#338 Added schematic_box to trace obstacles
  lib/components/primitive-components/Trace/Trace.ts
Labels: 💎 Bounty

#363 fix: bundle-size.yml file doesn't run on pr from forks
  .github/workflows/bundle-size.yml
Labels: 🙋 Bounty claim

#362 Implemented new event `renderable:renderLifecycle:anyEvent` to make it easier to listen to renderable events
  lib/Circuit.ts
  lib/components/base-components/Renderable.ts
Labels: 🙋 Bounty claim

#367 repro USB-C GND & VBUS route issue
  tests/features/remote-autorouting-1.test.tsx
  tests/features/remote-autorouting-2.test.tsx
  tests/repros/__snapshots__/repro6-USB-C-route-pcb.snap.svg
  tests/repros/repro6-USB-C-route.test.tsx
Labels: 🙋 Bounty claim

#355 preserve explicit component names in createUseComponent
  lib/hooks/create-use-component.tsx
  tests/components/normal-components/red-led-name-validation.test.tsx
Labels: 🙋 Bounty claim, no-pr-activity
