Repository tscircuit/core, pull requests merged in 2024-12, with the labels that each got.

#376 Support `root.schematicDisabled` to skip rendering all schematic components. With testing
  lib/Circuit.ts
  lib/components/base-components/NormalComponent.ts
  lib/components/normal-components/Chip.ts
  lib/components/normal-components/PinHeader.ts
  lib/components/primitive-components/NetAlias.ts
  lib/components/primitive-components/Trace/Trace.ts
  tests/examples/__snapshots__/example9-shcematicDisabled-schematic.snap.svg
  tests/examples/example9-shcematicDisabled.test.tsx
Labels: 🙋 Bounty claim

#378 Moved Schematic Text Logic to `SchematicComponentRenderWithSchematicBoxDimensions`
  lib/components/base-components/NormalComponent.ts
  lib/components/normal-components/Chip.ts
  lib/components/normal-components/PinHeader.ts
  tests/components/normal-components/__snapshots__/chip-complex-schematic-crossings-schematic.snap.svg
  tests/components/normal-components/__snapshots__/header-schematic.snap.svg
  tests/components/normal-components/__snapshots__/pin-header-schematic.snap.svg
  tests/examples/__snapshots__/example9-schematicDisabled-schematic.snap.svg
  tests/examples/example9-schematicDisabled.test.tsx
Labels: 🙋 Bounty claim

#381 feat: schDisplayLabel prop for <trace /> with test.
  bun.lockb
  lib/components/primitive-components/Trace/Trace.ts
  package.json
  tests/examples/__snapshots__/example10-schDisplayLabel-pcb.snap.svg
  tests/examples/__snapshots__/example10-schDisplayLabel-schematic.snap.svg
  tests/examples/example10-schDisplayLabel.test.tsx
Labels: 🙋 Bounty claim

#391 improve missing footprint error
  lib/components/base-components/NormalComponent.ts
Labels: no-pr-activity

#401 rotated rect obstacle test
  bun.lockb
  package.json
  tests/repros/__snapshots__/repro5-schematic-schematic.snap.svg
  tests/repros/__snapshots__/repro7-rotated-rect-obstacle-pcb.snap.svg
  tests/repros/repro7-rotated-rect-obstacle.test.tsx
Labels: 🙋 Bounty claim

#397 Automatic schematic net labeling for passive-chip for complex traces
  lib/components/primitive-components/Trace/Trace.ts
  lib/utils/schematic/countComplexElements.ts
  tests/components/normal-components/__snapshots__/chip-complex-crossings-simplified-1-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-complex-schematic-crossings-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-without-portarrangement-schematic.snap.svg
  tests/components/normal-components/__snapshots__/header-schematic.snap.svg
  tests/components/normal-components/__snapshots__/pin-header-schematic.snap.svg
  tests/examples/__snapshots__/bug-high-port-number-schematic.snap.svg
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
  tests/examples/example7-voltage-regulator-with-connections.test.tsx
  tests/repros/__snapshots__/repro5-schematic-schematic.snap.svg
Labels: 🙋 Bounty claim

#409 Implemented Root Circuit.ts pcbDisabled option to disable all pcb elements
  lib/Circuit.ts
  lib/components/base-components/NormalComponent.ts
  lib/components/normal-components/Board.ts
  lib/components/normal-components/Chip.ts
  lib/components/normal-components/Jumper.ts
  lib/components/primitive-components/FabricationNotePath.ts
  lib/components/primitive-components/FabricationNoteText.ts
  lib/components/primitive-components/Footprint.ts
  lib/components/primitive-components/Group/Group.ts
  lib/components/primitive-components/Hole.ts
  lib/components/primitive-components/Keepout.ts
  lib/components/primitive-components/Net.ts
  lib/components/primitive-components/PlatedHole.ts
  lib/components/primitive-components/Port.ts
  lib/components/primitive-components/SilkscreenCircle.ts
  lib/components/primitive-components/SilkscreenPath.ts
  lib/components/primitive-components/SilkscreenRect.ts
  lib/components/primitive-components/SilkscreenText.ts
  lib/components/primitive-components/SmtPad.ts
  lib/components/primitive-components/Trace/Trace.ts
  lib/components/primitive-components/TraceHint.ts
  lib/components/primitive-components/Via.ts
  tests/examples/__snapshots__/example9-schematic-and-pcb-disabled-pcb.snap.svg
  tests/examples/__snapshots__/example9-schematic-and-pcb-disabled-schematic.snap.svg
  tests/examples/example9-schematic-and-pcb-disabled.test.tsx
Labels: 🙋 Bounty claim

#422 feat:schematic_net_label.symbol_name for GND symbol.
  bun.lockb
  lib/components/primitive-components/Trace/Trace.ts
  lib/components/primitive-components/Trace/create-downward-net-label-ground-symbol.ts
  package.json
  tests/components/normal-components/__snapshots__/chip-complex-schematic-crossings-schematic.snap.svg
  tests/examples/__snapshots__/example10-schDisplayLabel-schematic.snap.svg
  tests/examples/__snapshots__/example11-net-symbol-schematic.snap.svg
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
  tests/examples/example11-net-symbol.test.tsx
  tests/repros/__snapshots__/repro5-schematic-schematic.snap.svg
Labels: 🙋 Bounty claim, 💰 Rewarded

#428 add silkscreen line component
  lib/components/index.ts
  lib/components/primitive-components/SilkscreenLine.ts
  tests/components/primitive-components/__snapshots__/silkscreen-line-pcb.snap.svg
  tests/components/primitive-components/silkscreen-line.test.tsx
Labels: 🙋 Bounty claim, 💰 Rewarded

#424 Set up continuous branch release with pkg-pr-new
  .github/workflows/branch-release.yml
  package.json
Labels: 🙋 Bounty claim, no-pr-activity

#459 add transistor
  bun.lockb
  lib/components/index.ts
  lib/components/normal-components/Transistor.ts
  lib/fiber/intrinsic-jsx.ts
  package.json
  tests/components/normal-components/__snapshots__/transistor.test.tsx.npn.0-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.npn.180-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.npn.270-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.npn.90-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.pnp.0-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.pnp.180-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.pnp.270-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor.test.tsx.pnp.90-schematic.snap.svg
  tests/components/normal-components/transistor.test.tsx
Labels: 🙋 Bounty claim

#442 add: resonator
  __snapshots__/resonator-default-schematic.snap.svg
  __snapshots__/resonator-no-ground-schematic.snap.svg
  __snapshots__/resonator-single-ground-schematic.snap.svg
  __snapshots__/resonator-two-ground-schematic.snap.svg
  bun.lockb
  lib/components/index.ts
  lib/components/normal-components/Resonator.ts
  lib/fiber/intrinsic-jsx.ts
  package.json
  tests/components/normal-components/__snapshots__/board-schematic-manual-edits-schematic.snap.svg
  tests/components/normal-components/__snapshots__/chip-port-without-portarrangement-schematic.snap.svg
  tests/components/normal-components/resonator.test.tsx
  tests/examples/__snapshots__/example10-schDisplayLabel-schematic.snap.svg
  tests/examples/__snapshots__/example4-kicad-schematic.snap.svg
  tests/examples/__snapshots__/example5-simple-circuit-schematic.snap.svg
  tests/examples/__snapshots__/example7-voltage-regulator-with-connections-schematic.snap.svg
Labels: 🙋 Bounty claim

#466 add source_component.display_value for resistor and capacitor
  bun.lockb
  lib/components/normal-components/Capacitor.ts
  lib/components/normal-components/Resistor.ts
  package.json
  tests/components/normal-components/capacitor-display-value.test.tsx
  tests/components/normal-components/resistor-display-value.test.tsx
Labels: 🙋 Bounty claim

#472 feat: trace constrains
  bun.lockb
  lib/components/normal-components/Capacitor.ts
  lib/components/primitive-components/Trace/Trace.ts
  lib/components/primitive-components/Trace/compute-trace-length.ts
  lib/components/primitive-components/Trace/get-max-length-from-conn ected-capacitors.ts
  package.json
  tests/examples/example13-trace-length.test.tsx
Labels: 💰 Rewarded
