Repository tscircuit/core, pull requests merged in 2025-05, with the labels that each got.

#775 Output PCB Solder Paste Objects for each Smtpad and Plated hole
  bun.lock
  lib/components/primitive-components/PlatedHole.ts
  lib/components/primitive-components/SmtPad.ts
  package.json
  tests/components/primitive-components/create-solderpaste-from-smtpad-and-plated-holes.test.tsx
Labels: 🙋 Bounty claim

#778 Trace hints now work with the new autorouter
  lib/components/base-components/Renderable.ts
  lib/components/primitive-components/Trace/Trace.ts
  lib/components/primitive-components/Trace/get-max-length-from-connected-capacitors.ts
  lib/utils/autorouting/getSimpleRouteJsonFromCircuitJson.ts
  tests/components/primitive-components/__snapshots__/multilayer-obstacle-route.snap.svg
  tests/components/primitive-components/__snapshots__/trace-hint-with-local-autorouter-pcb.snap.svg
  tests/components/primitive-components/trace-hint-with-local-autorouter.test.tsx
Labels: 🙋 Bounty claim

#781 fixing pnp transistor collector pin is numbered incorrectly
  lib/components/normal-components/Transistor.ts
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-base-pcb.snap.svg
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-base-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-collector-pcb.snap.svg
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-collector-schematic.snap.svg
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-emitter-pcb.snap.svg
  tests/components/normal-components/__snapshots__/transistor-pin-mapping-emitter-schematic.snap.svg
  tests/components/normal-components/transistor-pin-mapping-base.test.tsx
  tests/components/normal-components/transistor-pin-mapping-collector.test.tsx
  tests/components/normal-components/transistor-pin-mapping-emitter.test.tsx
Labels: 🙋 Bounty claim

#784 Feat: Enable pinLabels silkscreen with pinrow footprint
  bun.lock
  lib/components/base-components/NormalComponent/NormalComponent.ts
  lib/utils/createComponentsFromCircuitJson.ts
  lib/utils/createPinrowSilkscreenText.ts
  package.json
  tests/components/normal-components/__snapshots__/header-pcb.snap.svg
  tests/components/normal-components/__snapshots__/jumper.test.tsxrows-pcb.snap.svg
  tests/components/normal-components/jumper.test.tsx
  tests/examples/__snapshots__/example23-chip-pinlable-with-pinrow-footprint-silkscreen-pcb.snap.svg
  tests/examples/example23-chip-pinlable-with-pinrow-footprint-silkscreen.test.tsx
Labels: 🙋 Bounty claim

#790 Jumper internallyConnectedPins are now actually connected
  bun.lock
  lib/components/normal-components/Jumper.ts
  package.json
  tests/components/normal-components/solderjumper-circuit.test.tsx
Labels: 💰 Rewarded

#825 Add VIN and EN nets to selectors
  lib/sel/sel.ts
  tests/sel/sel1.test.ts
Labels: codex

#839 Add parts engine caching
  lib/augment-platform-config.d.ts
  lib/components/base-components/NormalComponent/NormalComponent.ts
  lib/index.ts
  lib/local-cache-engine.ts
  tests/components/normal-components/parts-engine-cache.test.tsx
Labels: codex
