Repository tscircuit/core, pull requests merged in 2025-09, with the labels that each got.

#1271 Skip rp2040 decoupling test and add benchmark
  benchmarking/all-benchmarks.tsx
  benchmarking/benchmarks/benchmark2-rp2040-decoupling-capacitors.tsx
  tests/repros/repro50-rp2040-decoupling-capacitors.test.tsx
Labels: codex

#1287 feat: Don't create components if there's a same-name naming conflict
  lib/components/base-components/NormalComponent/NormalComponent.ts
  lib/components/base-components/Renderable.ts
  tests/components/normal-components/__snapshots__/chip-rotation-smtpad-pcb.snap.svg
  tests/components/normal-components/chip-rotation-smtpad.test.tsx
  tests/components/normal-components/name-conflict-error.test.tsx
  tests/features/flex/__snapshots__/board-flex-pack-pcb.snap.svg
  tests/repros/__snapshots__/repro7-rotated-rect-obstacle-pcb.snap.svg
  tests/repros/repro7-rotated-rect-obstacle.test.tsx
Labels: 🙋 Bounty claim

#1283 feat: add manual via trace support
  lib/components/primitive-components/Port/Port.ts
  lib/components/primitive-components/Via.ts
  package.json
  tests/components/primitive-components/__snapshots__/via-connect-trace-pcb.snap.svg
  tests/components/primitive-components/__snapshots__/via-connect-trace-simple-3d.snap.svg
  tests/components/primitive-components/via-connect-trace.test.tsx
Labels: 🙋 Bounty claim

#1304 Fix intermittent boolean operation errors with calculate-packing update and unskip repro44
  package.json
  tests/repros/__snapshots__/repro44-e2e-pack-and-schematic-pcb.snap.svg
  tests/repros/repro44-e2e-pack-and-schematic.test.tsx
Labels: codex

#1317 chore(test): add thresholded svg snapshot matcher
  tests/fixtures/extend-expect-any-svg.ts
  tests/fixtures/preload.ts
Labels: codex

#1319 feat: surface external footprint load errors
  lib/components/base-components/NormalComponent/NormalComponent_doInitialPcbFootprintStringRender.ts
  package.json
  tests/external_footprint_load_error.test.ts
  tests/footprint/footprint-library-map-error.test.tsx
Labels: codex

#1325 feat: update cad model unit scale factor
  lib/components/base-components/NormalComponent/NormalComponent.ts
  package.json
  tests/components/normal-components/chip-cad-model-gltf.test.tsx
Labels: codex

#1370 feat: platedhole offsets for holes in plated pads
  lib/components/primitive-components/Hole.ts
  lib/components/primitive-components/PlatedHole.ts
  lib/utils/createComponentsFromCircuitJson.ts
  package.json
  tests/components/primitive-components/__snapshots__/pcb-circular-hole-rect-plated-offset-hole-pcb.snap.svg
  tests/components/primitive-components/pcb-circular-hole-rect-plated-offset-hole.test.tsx
Labels: 🙋 Bounty claim, codex

#1392 chore: update circuit-json-to-simple-3d
  package.json
Labels: codex

#1393 Add schematic arc and circle primitives
  lib/components/base-components/NormalComponent/NormalComponent.ts
  lib/components/index.ts
  lib/components/primitive-components/SchematicArc.ts
  lib/components/primitive-components/SchematicCircle.ts
  lib/fiber/intrinsic-jsx.ts
  lib/utils/autorouting/getBoundsForSchematic.ts
  tests/components/primitive-components/__snapshots__/schematic-arc-schematic.snap.svg
  tests/components/primitive-components/__snapshots__/schematic-circle-schematic.snap.svg
  tests/components/primitive-components/schematic-arc.test.tsx
  tests/components/primitive-components/schematic-circle.test.tsx
Labels: codex
